### ISSUE TITLE
statcast_search error: "Can't assign 92 names to a 94 column data.table"

### ISSUE THREAD

**Issue by OpeningDayBestDay** [BillPetti/baseballr#335]
When running statcast_search I get an error about a misalignment of number of columns. I suspect the website being scraped has added 2 new stats? Just a guess. Please let me know if/when this can be fixed. Screenshot attached.
<img width="536" alt="Statcast Search Issue" src="https://github.com/BillPetti/baseballr/assets/169717590/5481d0af-377c-41a6-b490-ec99ebac453d">

<img width="536" alt="Statcast Search Issue" src="https://github.com/BillPetti/baseballr/assets/169717590/a65c70ff-157f-40c0-b519-9c289e25c426">

**Comment by camdenk** [comment]
Download the dev version with devtools::install_github("BillPetti/baseballr") and this should be fixed!

**Comment by OpeningDayBestDay** [comment]
> Download the dev version with devtools::install_github("BillPetti/baseballr") and this should be fixed!

I am still getting the error. Maybe I am not connecting to the dev version correctly. Could you detail the steps to change connection to the dev version and run statcast_search?

**Comment by OpeningDayBestDay** [comment]
> > Download the dev version with devtools::install_github("BillPetti/baseballr") and this should be fixed!
> 
> I am still getting the error. Maybe I am not connecting to the dev version correctly. Could you detail the steps to change connection to the dev version and run statcast_search?

These are the steps I took:
1) Uninstall current package for baseballr
2) library(devtools)
3) devtools::install_github("BillPetti/baseballr", ref = "development_branch")

**Comment by camdenk** [comment]
The fix is in the main branch, not the development branch.

Steps:
1. Download the dev version with `devtools::install_github("BillPetti/baseballr")`
2. Restart your session 
3. Test new function

**Comment by OpeningDayBestDay** [comment]
> The fix is in the main branch, not the development branch.
> 
> Steps:
> 
> 1. Download the dev version with `devtools::install_github("BillPetti/baseballr")`
> 2. Restart your session
> 3. Test new function

I believe I was successful in pointing my code to dev version but not I am getting a different error and still cannot run the function: 
![image](https://github.com/BillPetti/baseballr/assets/169717590/9be60b69-2948-424c-b1bd-8f8649e24f4e)
